# Generated by Django 6.1.1 on 2026-09-15 17:08

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_resource_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.faculty_upload_path),
        ),
        migrations.AlterField(
            model_name='notice',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=api.models.notice_upload_path),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=api.models.resource_upload_path),
        ),
    ]
