# Generated by Django 6.1.1 on 2026-10-07 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_site_content_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('file', 'File'), ('link', 'External Link')], default='file', max_length=10),
        ),
        migrations.AddField(
            model_name='resource',
            name='url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
